import { Note } from './note'

export const NOTES: Note[] = [
  { id: 1, title: 'Arbeit', message: 'Very good spot long bois tungg heckin long doggo vvv shooberino, shoob shooberino vvv I am bekom fat. Corgo most angery pupper I have ever seen floofs you are doing me the shock puggorino aqua doggo long bois very good spot fat boi, thicc blep yapper pupperino woofer snoot tungg. I am bekom fat thicc pats big ol doing me a frighten, heckin porgo heckin. doggorino. Wow very biscit the neighborhood pupper ruff noodle horse thicc heckin good boys and girls, borkf you are doin me a concern long doggo. lotsa pats doge floofs. Pats borkf ruff stop it fren, corgo. Clouds tungg sub woofer yapper sub woofer blop vvv, you are doing me the shock shooberino smol clouds.', created: Date.now(), lastEdited: Date.now()},
  { id: 2, title: 'Universität', message: 'heckin pats very jealous pupper, lotsa pats boofers. Puggo tungg boof ruff you are doin me a concern, dat tungg tho blop shoob long bois, smol heckin puggo. Porgo you are doin me a concern the neighborhood pupper long bois doggorino, you are doing me a frighten borking doggo.', created: Date.now(), lastEdited: Date.now()},
  { id: 3, title: 'Cosplays', message: 'Mlem length boy boofers length boy much ruin diet, he made many woofs many pats doggo. Wow very biscit aqua doggo puggorino shibe, sub woofer vvv. Most angery pupper I have ever seen ruff doge noodle horse he made many woofs, very taste wow very jealous pupper big ol pupper, lotsa pats porgo you are doing me a frighten. Ur givin me a spook shibe heckin mlem, very good spot porgo.\n', created: Date.now(), lastEdited: Date.now()},
  { id: 4, title: 'Welteroberungspläne', message: 'neighborhood pupper ruff noodle horse thicc heckin good boys and girls, borkf you are doin me a concern long doggo. lotsa pats doge floofs. Pats borkf ruff stop it fren, corgo. Clouds tungg sub woofer yapper sub woofer blop vvv, you are doing me the shock shooberino smol clouds.', created: Date.now(), lastEdited: Date.now()},
  { id: 5, title: 'Katzenvideos', message: 'very good spot corgo shoob such treat, long water shoob heckin angery woofer. Shoober what a nice floof long doggo much ruin diet fluffer blop borkf, long water shoob you are doing me the shock the neighborhood pupper bork. Long bois ur givin me a spook blep, waggy wags. Long woofer maximum borkdrive tungg very good spot heckin good boys, fat boi wrinkler.', created: Date.now(), lastEdited: Date.now()},
]
